Repository apache/uima-uimaj, pull requests merged in 2022-04, with the labels that each got.

#188 UIMA-6430 upgrade commons-io due to cve
  PearPackagingMavenPlugin/pom.xml
Labels: refactoring

#191 [UIMA-6431] Use lambda functions as CAS processors
  uimaj-core/src/main/java/org/apache/uima/analysis_component/JCasProcessorAnnotator.java
Labels: enhancement

#192 [UIMA-6433] Update issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactoring

#195 [UIMA-6433] Update issue and PR templates
  pom.xml
Labels: refactoring

#194 [UIMA-6435] Vinci example descriptors do not work
  uimaj-examples/src/main/deploy/vinci/Deploy_MeetingDetectorTAE.xml
  uimaj-examples/src/main/deploy/vinci/Deploy_PersonTitleAnnotator.xml
  uimaj-examples/src/main/deploy/vinci/Deploy_XmiWriterWithTutorialTypeSystem.xml
Labels: bug

#193 [UIMA-6434] Some launch configs do not work
  uimaj-examples/src/main/eclipseProject/classpath
  uimaj-examples/src/main/run_configuration/UIMA CAS Visual Debugger.launch
  uimaj-examples/src/main/run_configuration/UIMA Document Analyzer.launch
  uimaj-examples/src/main/run_configuration/UIMA JCasGen.launch
  uimaj-examples/src/main/run_configuration/UIMA PEAR Installer.launch
  uimaj-examples/src/main/run_configuration/UIMA Run AE.launch
  uimaj-examples/src/main/run_configuration/UIMA Run CPE.launch
  uimaj-examples/src/main/run_configuration/UIMA Run V3 migrate JCas from classes roots.launch
  uimaj-examples/src/main/run_configuration/UIMA Run V3 migrate JCas from sources roots.launch
  uimaj-examples/src/main/run_configuration/UIMA Start VNS.launch
  uimaj-examples/src/main/run_configuration/UIMA Start Vinci Service.launch
Labels: bug

#196 [UIMA-6433] Update issue and PR templates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactoring

#198 [UIMA-6374] Create CAS (de)serialization test suite
  uimaj-core/src/main/java/org/apache/uima/resource/impl/RelativePathResolver_impl.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_BINARY_TSI_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_BINARY_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_COMPRESSED_FILTERED_TSI_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_SERIALIZED_TSI_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XCAS_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XMI_1_0_PRETTY_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XMI_1_1_PRETTY_Test.java
  uimaj-core/src/test/java/org/apache/uima/cas/serdes/scenario/SerRefTestScenario.java
  uimaj-core/src/test/java/org/apache/uima/resource/impl/RelativePathResolver_implTest.java
Labels: bug
